volumes:
  mysql:
  project:
  results:
  secrets:

services:
  mysql:
    image: ghcr.io/jehoonsong/ndist-mysql:latest
    build: 
      context: images/mysql
    volumes:
      - "mysql:/var/lib/mysql"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "3307:3306"
  apache:
    image: ghcr.io/jehoonsong/ndist-apache:latest
    build: 
      context: images/apache
      args:
        - BOINC_USER
        - PROJECT_ROOT
    hostname: $PROJECT
    depends_on:
      - mysql
    volumes: 
      - "./data:/data"
      - "project:$PROJECT_ROOT"
      - "results:/results"
      - "secrets:/run/secrets"
      - "/volume1/scratch:/scratch"
      #- "/dev/null:/run/secrets/keys/code_sign_private"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports: 
      - "8089:80"
    tty: true
    environment:
      - URL_BASE
      - PROJECT
  makeproject:
    #image: boinc/server_makeproject:$VERSION$TAG$DEFAULTARGS
    image: ghcr.io/jehoonsong/ndist-makeproject:latest
    build: 
      context: images/makeproject
      #target: makeproject$DEFAULTARGS
      args:
        - TAG
        - BOINC_USER
        - PROJECT_ROOT
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "secrets:/run/secrets"
    hostname: makeproject
    environment:
      - URL_BASE
      - PROJECT
    depends_on:
      - mysql
      - apache

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    #image: ghcr.io/jehoonsong/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    depends_on:
      - mysql
      - apache


  # boinncc:
  #   image: boinc/client
  #   environment:
  #     - BOINC_CMD_LINE_OPTIONS=--dir /var/lib/boinc-client --attach_project http://172.30.1.115/hello ba523f14280068c5d539b7d87ff47bef
  #   volumes:
  #     - boinc_data:/var/lib/boinc-client
  #   restart: unless-stopped

