version: "3.4"

volumes:
  mysql:
  project:
  results:
  secrets:

services:
  mysql:
    build: 
      context: images/mysql
    volumes:
      - "mysql:/var/lib/mysql"
#    depends_on:
#      - makeproject
 
  makeproject:
    build: 
      context: images/makeproject
      args:
        - BOINC_USER
        - PROJECT_ROOT
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "secrets:/run/secrets"
    hostname: makeproject
    environment:
      - URL_BASE
      - PROJECT

  apache:
    build: 
      context: images/apache
      args:
        - BOINC_USER
        - PROJECT_ROOT
    hostname: $PROJECT
    depends_on:
      - mysql
      - makeproject
    volumes: 
      - "$datadir:/data"
      - "$datadir/project/bin/boinc2docker_create_work.py:/home/boincadm/project/bin/boinc2docker_create_work.py"
      - "project:$PROJECT_ROOT"
      - "results:/results"
      - "secrets:/run/secrets"
      #- "/dev/null:/run/secrets/keys/code_sign_private"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports: 
      - "80:80"
    tty: true
    environment:
      - URL_BASE
      - PROJECT
    

# datadir=/Users/jehoons/boinc-server-docker/data docker-compose up 
