version: "2"

volumes:
  boinc_data:

services:
  example:
    build:
      context: .
      dockerfile: Dockerfile.arm64v8
      args:
        - platform=linux/arm64
    image: boincc:latest
    environment:
      - BOINC_CMD_LINE_OPTIONS=--dir /var/lib/boinc --attach_project http://172.30.1.115/hello ${USER_ACCOUNT_KEY}
    
    volumes:
      - boinc_data:/var/lib/boinc
      - ./cc_config.xml:/etc/boinc-client/cc_config.xml

    restart: unless-stopped
