version: "2"

volumes:
  ndistc_data:

services:
  ndistc:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    image: ghcr.io/jehoonsong/boincc:latest
    #environment:
    volumes:
      - ndistc_data:/var/lib/boinc
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cc_config.xml:/var/lib/boinc/cc_config.xml
      - ./app_config.xml:${APPCONFDIR}

    restart: unless-stopped
