version: "2"

volumes:
  boinc_data:

services:
  example:
    build:
      context: .
      dockerfile: Dockerfile.arm64v8
      args:
        - platform=linux/arm64
    image: boincc:latest
    environment:
      - BOINC_CMD_LINE_OPTIONS=--dir /var/lib/boinc --attach_project ${BOINC_PROJECT_URL} ${BOINC_ACCOUNT_KEY}
      - BOINC_REMOTE_HOST=${BOINC_REMOTE_HOST}
      - BOINC_PROJECT_URL=${BOINC_PROJECT_URL}
      - BOINC_ACCOUNT_KEY=${BOINC_ACCOUNT_KEY}
    volumes:
      - boinc_data:/var/lib/boinc
      - ./cc_config.xml:/etc/boinc-client/cc_config.xml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
