volumes:
  boinc_data:

services:
  boinc-client:
    image: boinc/client
    environment:
      - BOINC_CMD_LINE_OPTIONS=--attach_project http://192.168.0.234/boincserver bc65a525ed1cc74a6ab83ca6cb8da4f3
    volumes:
      - boinc_data:/var/lib/boinc
    restart: unless-stopped
